workdir: config["workdir"]


shell.executable("/bin/bash")
shell.prefix("set +eu;")


rule all:
    input:
        "multiqc",
        "qc-summary/panel-qc-summary.xlsx",
        "variant/all-vars-summary.tsv",


include: "rules/ref.smk"
include: "rules/bed.smk"
include: "rules/fastqc.smk"
include: "rules/fastp.smk"
include: "rules/map.smk"
include: "rules/qc_summary.smk"
include: "rules/trim_primer.smk"
include: "rules/lowcov.smk"
include: "rules/var.smk"
